# Replace the text below to customize your site
site_name: Marius Schairer - MDEF & Fab Lab Barcelona
site_description: Master in Design for Emergent Futures
site_author: Marius Schairer
copyright: Copyleft 2023 "Marius Schairer" - GNU Free Documentation License
repo_name: 'Name : Github Repo'
site_url: https://marius-schairer.github.io/MDEF_Documentation/
repo_url: 'https://github.com/marius-schairer/MDEF_Documentation'

nav:
  - Overview: index.md
  - Thesis Project: thesis_project.md
  - Design Studio:
    - 01 Roles of Prototyping: term1/Design/RolesofPrototyping.md
    - 02 Collective Design Space: term1/Design/CollectiveDesignSpace.md
    - 03 Narratives: term1/Design/Narratives.md
    - 04 Collective Intervention: term1/Design/CollectiveIntervention.md
    - 05 Design Dialogues: term2/DesignStudio02/Dialogues.md
    - 06 Intervention 01: term2/DesignStudio02/Intervention01.md
    - 07 Intervention 02: term2/DesignStudio02/Intervention02.md
    - 08 Intervention 03: term2/DesignStudio02/Intervention03.md
    - 09 Connect with Community's: term3/DesignStudio03/intervention1.md
    - 10 Workshops : term3/DesignStudio03/intervention2.md
  - Year 2:
    - Reflections:
        - Emerging Economies: year2/Emerging_Economies.md
        - Co-Creating Public Spaces: year2/Co-CreatingPublicSpaces.md
        - Interaction & Prototyping: year2/InteractionPrototyping.md
  - Year 1:
    - Research Trip: term2/ResearchTrip.md  
    - LAIA Project: term3/LAIAProject.md
    - Reflections:
        - Landing: term1/Landing/landing.md
        - AoWS: term1/Reflections/AtlasofWeakSignals.md
        - Documenting Design: term1/Reflections/DocumentingDesign.md
        - Living with Your Own Ideas: term1/Reflections/LwYoI.md
        - Bio & Agri Zero:
            - Bio Zero: term1/Reflections/BioZero.md
            - Agri Zero: term1/Reflections/AgriZero.md
            - GMO: term1/Reflections/GMO.md
        - Design with Others: term1/Reflections/DesignWithOthers.md
        - Extended intelligences: term1/Reflections/ExtendedIntelligences.md
        - Design for Climate Emergency: term2/Reflections/DesignforClimateEmergency.md
        - Future Talks:
            - Future Talk 01: term2/Reflections/FutureTalk/FutureTalks01.md
            - Future Talk 02: term2/Reflections/FutureTalk/FutureTalks02.md
        - Communicationg Ideas:
            - Communicating Ideas 01: term2/Reflections/CommunicatingIdeas/CommunicatingIdeas01.md
            - Communicating Ideas 02: term2/Reflections/CommunicatingIdeas/CommunicatingIdeas02.md
            - Communicating Ideas 03: term2/Reflections/CommunicatingIdeas/CommunicatingIdeas03.md
        - Fair Future(s): term2/Reflections/DesignWithCollectiveIntelligences.md
        - Measuring the World: term2/Reflections/MeasuringTheWorld.md
        - Extended Intelligences: term2/Reflections/ExtendedIntelligences.md
        - Atlas of Weak Signals: term3/Reflections/TheAtlasOfWeakSignals.md
        - Communicating Ideas: term3/Reflections/CommunicatingIdeas.md
        - FutureTalks:
            Helen Torres: term3/Reflections/FutureTalk/FutureTalk01.md
            Aqui Clémens: term3/Reflections/FutureTalk/FutureTalk02.md
            Krzysztof Wronski: term3/Reflections/FutureTalk/FutureTalk03.md
        - Design Ethics: term3/Reflections/DesignEthics.md
        - Critical Transfeminist Design: term3/Reflections/CriticalTransfeministDesign.md 
  - with Fablab:
    - Fabricademy:  
        - Biochromes: year2/BioChrome.md
        - Soft Robotics: year2/Soft-Robotics.md
    - Fabacademy: 
        - Electronics: year2/Fabacademy/electronics.md
    - Machine Paradox: term1/Reflections/MachineParadox.md
    - Digital Prototyping for Design: 
        - Challenge 01: term2/Reflections/DigitalFabrication/DigitalFabrication01.md
        - Challenge 02: term2/Reflections/DigitalFabrication/DigitalFabrication02.md
        - Challange 03: term3/DPFD/DigitalPrototypingForDesign01.md
        - Challange 04: term3/DPFD/DigitalPrototypingForDesign02.md
        - Challange 05: term3/DPFD/DigitalPrototypingForDesign05.md
    - Micro Challange:
        - Challange 01: term2/MicroChallange/Challange01.md
        - Challange 02: term2/MicroChallange/Challange02.md
        - Micro Challage 3: term3/MicroChallange03.md
  - About: about/me.md
  
        
        



extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/instagram
      link: "https://instagram.com/design.from.mars?igshid=OGQ5ZDc2ODk2ZA=="
    - icon: fontawesome/brands/linkedin
      link: "https://de.linkedin.com/in/marius-patric-schairer-00a505207"
    - icon: fontawesome/brands/github
      link: "https://github.com/marius-schairer"

theme:
  name: material
  custom_dir: overrides
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: white
    accent: purple
  font:
    # See available fonts at https://fonts.google.com/
    text: Roboto
    code: Roboto Mono

  logo: images/Logos/ColorLogo.png
  favicon: images/Logos/ColorLogo.png
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - overrides/stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
